import Link from "next/link";
import { Zap, Ghost, BookOpen, CheckSquare, Dumbbell, User } from "lucide-react";

const SECTIONS = [
  { icon: CheckSquare, href:"/docs/checkin",  title:"Daily Check-In",    desc:"Tell VYTALL how you feel today. It listens, interprets, and decides what you need." },
  { icon: Zap,         href:"/docs/mission",  title:"Your Daily Mission", desc:"Not a generic workout. A prescription built for today's version of you." },
  { icon: Ghost,       href:"/docs/ghost",    title:"The Ghost",          desc:"The strongest version of you, ever. VYTALL tracks it — and compares you to it." },
  { icon: BookOpen,    href:"/docs/archive",  title:"Your Archive",       desc:"Your training story. Chapters, eras, setbacks, and breakthroughs — all remembered." },
  { icon: Dumbbell,    href:"/docs/workouts", title:"Logging Workouts",   desc:"Track your sessions. VYTALL reflects on them and prepares you for tomorrow." },
  { icon: User,        href:"/docs/profile",  title:"Your Profile",       desc:"Your goals, equipment, schedule. The foundation VYTALL builds everything on." },
];

export default function DocsIndex() {
  return (
    <>
      <style>{`
        .doc-card { background:var(--graphite); border:1px solid var(--border); border-radius:12px; padding:20px; text-decoration:none; display:block; transition:border-color .2s,transform .2s; }
        .doc-card:hover { border-color:var(--vital); transform:translateY(-2px); }
      `}</style>

      <h1>How VYTALL Works</h1>
      <p className="doc-lead">
        VYTALL is your AI training coach — one that actually remembers you. It studies your patterns day by day, reads how you feel, and tells you exactly what your body needs today. Not a template. Not a guess. A prescription.
      </p>

      <div className="doc-callout">
        <p><strong>VYTALL is powered by AI.</strong> Every mission, every reflection, every Ghost comparison is generated by an AI coach that knows your history — your best weeks, your hardest setbacks, and everything in between.</p>
      </div>

      <h2>The Idea</h2>
      <p>Most fitness apps give you the same plan as everyone else. They don't know that you slept 4 hours last night. They don't know you trained hard three days in a row. They don't remember the week you were at your best.</p>
      <p><strong>VYTALL does.</strong> It builds a memory of you as an athlete — and every day, it uses that memory to coach you better.</p>

      <h2>How a Day with VYTALL Looks</h2>
      <div style={{ display:"flex", flexDirection:"column", gap:"0" }}>
        {[
          { step:"01", title:"Check in",     desc:"You tell VYTALL your energy, sleep, soreness, mood, and how much time you have. Takes under 90 seconds." },
          { step:"02", title:"Get your mission", desc:"VYTALL reads your state, checks your history, and gives you today's training prescription. Intensity, focus, what to prioritize." },
          { step:"03", title:"Train",        desc:"Do the session. Log it when you're done — sets, reps, duration, how it felt." },
          { step:"04", title:"Get a reflection", desc:"VYTALL tells you what improved, what to watch, and what tomorrow probably needs." },
          { step:"05", title:"Build your story", desc:"Over time, VYTALL writes your Archive — chapters of your training life. And it tracks your Ghost: your strongest self, ever." },
        ].map((s, i, arr) => (
          <div key={s.step} style={{ display:"flex", gap:"16px", paddingBottom:"20px", borderLeft:"1px solid var(--border)", marginLeft:"16px", paddingLeft:"20px", position:"relative", paddingTop: i===0?"0":"20px" }}>
            <div style={{ position:"absolute", left:"-10px", top: i===0?"4px":"24px", width:"20px", height:"20px", borderRadius:"50%", background:"var(--vital)", display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0 }}>
              <span style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:".42rem", color:"#f5f2ee", letterSpacing:".05em" }}>{s.step}</span>
            </div>
            <div style={{ paddingLeft:"8px" }}>
              <div style={{ fontFamily:"'Barlow Condensed',sans-serif", fontSize:"1.05rem", fontWeight:700, letterSpacing:".06em", textTransform:"uppercase", color:"var(--bone)", marginBottom:"4px" }}>{s.title}</div>
              <div style={{ fontSize:".88rem", color:"var(--ghost)", lineHeight:1.6 }}>{s.desc}</div>
            </div>
          </div>
        ))}
      </div>

      <h2>Explore</h2>
      <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))", gap:"12px", marginTop:"16px" }}>
        {SECTIONS.map(s => (
          <Link key={s.href} href={s.href} className="doc-card">
            <s.icon size={16} color="var(--vital)" style={{ marginBottom:"10px" }} />
            <div style={{ fontFamily:"'Barlow Condensed',sans-serif", fontSize:".95rem", fontWeight:700, letterSpacing:".06em", textTransform:"uppercase", color:"var(--bone)", marginBottom:"4px" }}>{s.title}</div>
            <div style={{ fontSize:".82rem", color:"var(--ghost)", lineHeight:1.5 }}>{s.desc}</div>
          </Link>
        ))}
      </div>
    </>
  );
}
